baseURL: "https://nineteenventures.co/" 
title: Nineteen Ventures
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: "Nineteen Ventures builds and scales delightful solo and micro businesses in tech, marketing, lifstyle, ethical and environmental spaces. "
    author: Nineteen Ventures
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nineteen Ventures
          subtitle: "Nineteen Ventures builds and scales delightful solo and micro businesses. We are people who care deeply about customers, quality and integrity. We know who we are. We love what we do. We refuse to compromise on what's important to us.<br><br>Got questions or want to chat? Get in touch with us by clicking the email icon below."
          imageUrl: "light-mode-logo.svg"
          imageUrlDark: "dark-mode-logo.svg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: Email
          url: mailto:help@nineteenventures.co
       
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "Night Mode"
      # icon: favicon.ico
      # iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
